// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.onlinejob.domain;

import es.uca.iw.onlinejob.domain.Ciudad;

privileged aspect Ciudad_Roo_JavaBean {
    
    public String Ciudad.getNombre() {
        return this.nombre;
    }
    
    public void Ciudad.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
