// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.onlinejob.domain;

import es.uca.iw.onlinejob.domain.Demandante;
import es.uca.iw.onlinejob.domain.DemandanteDataOnDemand;
import es.uca.iw.onlinejob.domain.OfertaTrabajoDataOnDemand;
import es.uca.iw.onlinejob.domain.PerfilDataOnDemand;
import es.uca.iw.onlinejob.domain.UsuarioDataOnDemand;
import es.uca.iw.onlinejob.reference.EstadoOferta;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DemandanteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DemandanteDataOnDemand: @Component;
    
    private Random DemandanteDataOnDemand.rnd = new SecureRandom();
    
    private List<Demandante> DemandanteDataOnDemand.data;
    
    @Autowired
    OfertaTrabajoDataOnDemand DemandanteDataOnDemand.ofertaTrabajoDataOnDemand;
    
    @Autowired
    PerfilDataOnDemand DemandanteDataOnDemand.perfilDataOnDemand;
    
    @Autowired
    UsuarioDataOnDemand DemandanteDataOnDemand.usuarioDataOnDemand;
    
    public Demandante DemandanteDataOnDemand.getNewTransientDemandante(int index) {
        Demandante obj = new Demandante();
        setDireccion(obj, index);
        setDni(obj, index);
        setEmail(obj, index);
        setEstado(obj, index);
        setFecha_nacimiento(obj, index);
        setNombre(obj, index);
        setSexo(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void DemandanteDataOnDemand.setDireccion(Demandante obj, int index) {
        String direccion = "direccion_" + index;
        obj.setDireccion(direccion);
    }
    
    public void DemandanteDataOnDemand.setDni(Demandante obj, int index) {
        String dni = "dni_" + index;
        obj.setDni(dni);
    }
    
    public void DemandanteDataOnDemand.setEmail(Demandante obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 32) {
            email = email.substring(0, 32);
        }
        obj.setEmail(email);
    }
    
    public void DemandanteDataOnDemand.setEstado(Demandante obj, int index) {
        EstadoOferta estado = EstadoOferta.class.getEnumConstants()[0];
        obj.setEstado(estado);
    }
    
    public void DemandanteDataOnDemand.setFecha_nacimiento(Demandante obj, int index) {
        Date fecha_nacimiento = new Date(new Date().getTime() - 10000000L);
        obj.setFecha_nacimiento(fecha_nacimiento);
    }
    
    public void DemandanteDataOnDemand.setNombre(Demandante obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 32) {
            nombre = nombre.substring(0, 32);
        }
        obj.setNombre(nombre);
    }
    
    public void DemandanteDataOnDemand.setSexo(Demandante obj, int index) {
        String sexo = "sexo_" + index;
        obj.setSexo(sexo);
    }
    
    public void DemandanteDataOnDemand.setTelefono(Demandante obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public Demandante DemandanteDataOnDemand.getSpecificDemandante(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Demandante obj = data.get(index);
        Long id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public Demandante DemandanteDataOnDemand.getRandomDemandante() {
        init();
        Demandante obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public boolean DemandanteDataOnDemand.modifyDemandante(Demandante obj) {
        return false;
    }
    
    public void DemandanteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Demandante.findDemandanteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Demandante' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Demandante>();
        for (int i = 0; i < 10; i++) {
            Demandante obj = getNewTransientDemandante(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
