// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.onlinejob.domain;

import es.uca.iw.onlinejob.domain.Direccion;
import es.uca.iw.onlinejob.domain.DireccionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DireccionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DireccionDataOnDemand: @Component;
    
    private Random DireccionDataOnDemand.rnd = new SecureRandom();
    
    private List<Direccion> DireccionDataOnDemand.data;
    
    public Direccion DireccionDataOnDemand.getNewTransientDireccion(int index) {
        Direccion obj = new Direccion();
        setCp(obj, index);
        setNombre(obj, index);
        setNum(obj, index);
        return obj;
    }
    
    public void DireccionDataOnDemand.setCp(Direccion obj, int index) {
        String cp = "cp_" + index;
        obj.setCp(cp);
    }
    
    public void DireccionDataOnDemand.setNombre(Direccion obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 32) {
            nombre = nombre.substring(0, 32);
        }
        obj.setNombre(nombre);
    }
    
    public void DireccionDataOnDemand.setNum(Direccion obj, int index) {
        String num = "num_" + index;
        obj.setNum(num);
    }
    
    public Direccion DireccionDataOnDemand.getSpecificDireccion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Direccion obj = data.get(index);
        Long id = obj.getId();
        return Direccion.findDireccion(id);
    }
    
    public Direccion DireccionDataOnDemand.getRandomDireccion() {
        init();
        Direccion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Direccion.findDireccion(id);
    }
    
    public boolean DireccionDataOnDemand.modifyDireccion(Direccion obj) {
        return false;
    }
    
    public void DireccionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Direccion.findDireccionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Direccion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Direccion>();
        for (int i = 0; i < 10; i++) {
            Direccion obj = getNewTransientDireccion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
